//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcChurchsj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evtable
    {
        public int eid { get; set; }
        public string etitle { get; set; }
        public string edate { get; set; }
        public string etext { get; set; }
    }
}
