//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcChurchsj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newstable
    {
        public int Nid { get; set; }
        public string Nhead { get; set; }
        public string Ndate { get; set; }
        public string NUrl { get; set; }
        public string Ntext { get; set; }
    }
}
